# Generated by Django 4.0.3 on 2022-04-08 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbClienteExterno',
            fields=[
                ('cle_cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('cle_razaosocial', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cle_unidade', models.CharField(max_length=50, null=True, verbose_name='Unidade')),
                ('cle_ie', models.CharField(max_length=12, null=True, verbose_name='Inscrição Estadual')),
                ('cle_im', models.CharField(max_length=11, null=True, verbose_name='Inscrição Municipal')),
                ('cle_endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('cle_numero', models.IntegerField(verbose_name='Número')),
                ('cle_complemento', models.CharField(max_length=100, null=True, verbose_name='Complemento')),
                ('cle_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cle_cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cle_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cle_uf', models.CharField(max_length=50, verbose_name='Estado')),
                ('cle_fone1', models.CharField(max_length=13, verbose_name='Telefone 1')),
                ('cle_cel', models.CharField(max_length=14, null=True, verbose_name='Celular')),
                ('cle_datacriacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cle_dataatualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbTermo',
            fields=[
                ('ter_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Termo ID')),
                ('ter_nome', models.CharField(max_length=45, verbose_name='Nome Termo')),
            ],
        ),
        migrations.CreateModel(
            name='tbVersaoTermo',
            fields=[
                ('vte_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Versão Termo ID')),
                ('vte_versao', models.CharField(max_length=10, verbose_name='Versão Termo')),
                ('vte_conteudo', models.CharField(max_length=1000, verbose_name='Conteudo Termo')),
                ('fk_ter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbtermo', verbose_name='ID Termo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_cpf', models.CharField(max_length=45, verbose_name='CPF')),
                ('usr_telefone', models.CharField(max_length=45, null=True, verbose_name='Telefone')),
                ('usr_datacriacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('usr_dataatualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_vte_usr',
            fields=[
                ('vte_usr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='VTE X USR')),
                ('fk_usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID Usuário')),
                ('fk_vte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbversaotermo', verbose_name='ID Versão Termo')),
            ],
            options={
                'unique_together': {('fk_usr_id', 'fk_vte_id')},
            },
        ),
        migrations.CreateModel(
            name='tb_usr_cle',
            fields=[
                ('usr_cle_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='USR X CLE')),
                ('fk_cle_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbclienteexterno', verbose_name='Cliente Externo ID')),
                ('fk_usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário ID')),
            ],
            options={
                'unique_together': {('fk_usr_id', 'fk_cle_cnpj')},
            },
        ),
        migrations.CreateModel(
            name='tb_cle_gpa',
            fields=[
                ('cle_gpa_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='CLE X GPA')),
                ('fk_cle_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbclienteexterno', verbose_name='Cnpj Cliente Externo')),
                ('fk_gpa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo Acesso ID')),
            ],
            options={
                'unique_together': {('fk_cle_cnpj', 'fk_gpa_id')},
            },
        ),
    ]
