# Generated by Django 4.0.3 on 2022-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_cle_gpa',
            name='cle_gpa_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='CLE X GPA'),
        ),
        migrations.AlterField(
            model_name='tb_usr_cle',
            name='usr_cle_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='USR X CLE'),
        ),
        migrations.AlterField(
            model_name='tb_vte_usr',
            name='vte_usr_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='VTE X USR'),
        ),
        migrations.AlterField(
            model_name='tbclienteexterno',
            name='cle_cnpj',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tbclienteexterno',
            name='cle_numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tbtermo',
            name='ter_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Termo ID'),
        ),
        migrations.AlterField(
            model_name='tbversaotermo',
            name='vte_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Versão Termo ID'),
        ),
    ]
