# Generated by Django 4.0.3 on 2022-04-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tb_cle_gpa_cle_gpa_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_cle_gpa',
        ),
    ]
