# Generated by Django 4.0.3 on 2022-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_tb_cle_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usr_aceitaCookies',
            field=models.BooleanField(default=False, verbose_name='Aceita Cookies?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='usr_conteudoMarketing',
            field=models.BooleanField(default=False, verbose_name='Aceita Marketing Opt-in Opt-out?'),
        ),
    ]
