# Generated by Django 4.0.3 on 2022-04-21 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historico_aceite_usuario_termo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_exclusao_usuario',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='historico_exclusao_usuario',
            name='data_exclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Exclusão'),
            preserve_default=False,
        ),
    ]
