# Generated by Django 4.0.3 on 2022-04-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_historico_exclusao_usuario_data_criacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historico_terceiro_sem_usuario',
        ),
        migrations.RemoveField(
            model_name='historico_usuario_terceiro',
            name='data_adicao',
        ),
        migrations.AddField(
            model_name='historico_usuario_terceiro',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Criação'),
        ),
    ]
