# Generated by Django 4.0.3 on 2022-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_historico_terceiro_sem_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_aceite_usuario_termo',
            name='data_aceite',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Aceite'),
        ),
    ]
