# Generated by Django 4.0.3 on 2022-04-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tbversaotermo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_aceite_usuario_termo',
            name='versao_termo',
            field=models.CharField(max_length=10, verbose_name='Versão Termo'),
        ),
    ]
